server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    error_page 404 /404.html;
    location / {
        try_files $uri $uri/ =404;
    }
    location ~* \.(css|js|png|jpg|jpeg|webp|svg|ico|xml|txt)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
